import { Trip } from './storage'

export const EXAMPLE_TRIPS: Trip[] = [
  {
    id: 'example-tokyo-2024',
    title: 'Tokyo Adventure',
    startDate: '2024-04-01',
    endDate: '2024-04-14',
    description: 'Explore the vibrant streets of Tokyo, from ancient temples to cutting-edge technology',
    emoji: '🗾',
    places: [
      {
        id: 'tokyo-shibuya',
        name: 'Shibuya Crossing',
        location: 'Shibuya',
        country: 'Japan',
        lat: 35.6595,
        lng: 139.7004,
        arrival: '10:00',
        departure: '17:00',
        day: 1,
        notes: 'Busiest pedestrian crossing in the world. Best visited during peak hours.',
        events: [],
        documents: [],
        links: []
      },
      {
        id: 'tokyo-senso',
        name: 'Senso-ji Temple',
        location: 'Asakusa',
        country: 'Japan',
        lat: 35.7148,
        lng: 139.7967,
        arrival: '09:00',
        departure: '12:00',
        day: 2,
        notes: 'One of Tokyo\'s oldest temples with beautiful red lantern.',
        events: [],
        documents: [],
        links: []
      },
      {
        id: 'tokyo-meiji',
        name: 'Meiji Shrine',
        location: 'Shibuya',
        country: 'Japan',
        lat: 35.6762,
        lng: 139.6993,
        arrival: '14:00',
        departure: '16:30',
        day: 3,
        notes: 'Peaceful shrine surrounded by forest. Great for experiencing traditional Japan.',
        events: [],
        documents: [],
        links: []
      },
      {
        id: 'tokyo-teamlab',
        name: 'teamLab Borderless',
        location: 'Odaiba',
        country: 'Japan',
        lat: 35.6326,
        lng: 139.7587,
        arrival: '10:00',
        departure: '18:00',
        day: 4,
        notes: 'Mind-bending digital art museum. Book tickets in advance.',
        events: [],
        documents: [],
        links: []
      },
      {
        id: 'tokyo-tsukiji',
        name: 'Tsukiji Outer Market',
        location: 'Chuo',
        country: 'Japan',
        lat: 35.6654,
        lng: 139.7709,
        arrival: '06:00',
        departure: '11:00',
        day: 5,
        notes: 'Fresh seafood and local delicacies. Great for breakfast and sushi.',
        events: [],
        documents: [],
        links: []
      }
    ]
  },
  {
    id: 'example-europe-2024',
    title: 'European Escape',
    startDate: '2024-05-10',
    endDate: '2024-05-31',
    description: 'A grand tour across Europe: Paris, Amsterdam, and Barcelona',
    emoji: '✈️',
    places: [
      {
        id: 'paris-eiffel',
        name: 'Eiffel Tower',
        location: 'Paris',
        country: 'France',
        lat: 48.8584,
        lng: 2.2945,
        arrival: '09:00',
        departure: '18:00',
        day: 1,
        notes: 'Book tickets online to skip the long queues. Best at sunset.',
        events: [],
        documents: [],
        links: []
      },
      {
        id: 'paris-louvre',
        name: 'Louvre Museum',
        location: 'Paris',
        country: 'France',
        lat: 48.8606,
        lng: 2.3352,
        arrival: '10:00',
        departure: '17:00',
        day: 2,
        notes: 'Home to the Mona Lisa. Closed Tuesdays.',
        events: [],
        documents: [],
        links: []
      },
      {
        id: 'paris-notre',
        name: 'Notre-Dame Cathedral',
        location: 'Paris',
        country: 'France',
        lat: 48.8530,
        lng: 2.3499,
        arrival: '14:00',
        departure: '17:00',
        day: 3,
        notes: 'Iconic Gothic architecture. Currently under restoration.',
        events: [],
        documents: [],
        links: []
      },
      {
        id: 'amsterdam-canal',
        name: 'Amsterdam Canal Tour',
        location: 'Amsterdam',
        country: 'Netherlands',
        lat: 52.3676,
        lng: 4.9041,
        arrival: '10:00',
        departure: '12:00',
        day: 5,
        notes: 'Best way to see the city. Many tour operators available.',
        events: [],
        documents: [],
        links: []
      },
      {
        id: 'amsterdam-museum',
        name: 'Van Gogh Museum',
        location: 'Amsterdam',
        country: 'Netherlands',
        lat: 52.3585,
        lng: 4.8813,
        arrival: '13:00',
        departure: '17:00',
        day: 6,
        notes: 'World\'s largest collection of Van Gogh\'s works.',
        events: [],
        documents: [],
        links: []
      },
      {
        id: 'barcelona-sagrada',
        name: 'Sagrada Familia',
        location: 'Barcelona',
        country: 'Spain',
        lat: 41.4036,
        lng: 2.1744,
        arrival: '10:00',
        departure: '16:00',
        day: 8,
        notes: 'Gaudí\'s masterpiece. Still under construction but breathtaking.',
        events: [],
        documents: [],
        links: []
      },
      {
        id: 'barcelona-park',
        name: 'Park Güell',
        location: 'Barcelona',
        country: 'Spain',
        lat: 41.4145,
        lng: 2.1527,
        arrival: '09:00',
        departure: '13:00',
        day: 9,
        notes: 'Colorful mosaic park with stunning city views.',
        events: [],
        documents: [],
        links: []
      },
      {
        id: 'barcelona-beach',
        name: 'Barceloneta Beach',
        location: 'Barcelona',
        country: 'Spain',
        lat: 41.3850,
        lng: 2.1734,
        arrival: '15:00',
        departure: '19:00',
        day: 10,
        notes: 'Popular beach for swimming and sunset drinks.',
        events: [],
        documents: [],
        links: []
      }
    ]
  },
  {
    id: 'example-bali-2024',
    title: 'Bali Island Bliss',
    startDate: '2024-06-15',
    endDate: '2024-06-29',
    description: 'Relax and explore the tropical paradise of Bali',
    emoji: '🏝️',
    places: [
      {
        id: 'bali-ubud',
        name: 'Ubud Town',
        location: 'Ubud',
        country: 'Indonesia',
        lat: -8.5069,
        lng: 115.2625,
        arrival: '09:00',
        departure: '17:00',
        day: 1,
        notes: 'Cultural heart of Bali. Great for art, food, and culture.',
        events: [],
        documents: [],
        links: []
      },
      {
        id: 'bali-monkey',
        name: 'Sacred Monkey Forest',
        location: 'Ubud',
        country: 'Indonesia',
        lat: -8.5151,
        lng: 115.2587,
        arrival: '10:00',
        departure: '12:00',
        day: 2,
        notes: 'Ancient temple sanctuary. Be careful with belongings around monkeys.',
        events: [],
        documents: [],
        links: []
      },
      {
        id: 'bali-rice-terraces',
        name: 'Tegallalang Rice Terraces',
        location: 'Ubud',
        country: 'Indonesia',
        lat: -8.4300,
        lng: 115.2631,
        arrival: '08:00',
        departure: '11:00',
        day: 3,
        notes: 'Stunning green rice paddies. Best visited early morning.',
        events: [],
        documents: [],
        links: []
      },
      {
        id: 'bali-seminyak',
        name: 'Seminyak Beach',
        location: 'Seminyak',
        country: 'Indonesia',
        lat: -8.6896,
        lng: 115.1697,
        arrival: '15:00',
        departure: '19:00',
        day: 5,
        notes: 'Modern beach resort area with great restaurants and nightlife.',
        events: [],
        documents: [],
        links: []
      },
      {
        id: 'bali-tanah-lot',
        name: 'Tanah Lot Temple',
        location: 'Tabanan',
        country: 'Indonesia',
        lat: -8.6276,
        lng: 115.1419,
        arrival: '16:00',
        departure: '18:30',
        day: 6,
        notes: 'Iconic clifftop temple. Magical at sunset.',
        events: [],
        documents: [],
        links: []
      },
      {
        id: 'bali-gili-islands',
        name: 'Gili Islands',
        location: 'Gili Air',
        country: 'Indonesia',
        lat: -8.3580,
        lng: 115.6789,
        arrival: '10:00',
        departure: '17:00',
        day: 8,
        notes: 'Car-free islands perfect for relaxation and snorkeling.',
        events: [],
        documents: [],
        links: []
      }
    ]
  }
]

export function getRandomExampleTrips(count: number = 2): Trip[] {
  const shuffled = [...EXAMPLE_TRIPS].sort(() => Math.random() - 0.5)
  return shuffled.slice(0, Math.min(count, EXAMPLE_TRIPS.length))
}
